### ISSUE TITLE
HZH 's blog

### ISSUE THREAD

**Issue by BowenYoung** [BowenYoung/friendLinks-api#16]
```json
{
    "title": "宏的自留地",
    "url": "https://arcitcgn.cn/",
    "avatar": "https://oc.arcitcgn.cn/2022/07/11/62cbadded38bf.jpg",
    "screenshot": "https://bu.dusays.com/2022/07/16/62d2759e20525.png",
    "description": "好折腾的小生",
    "keywords": ""
}
```

我的友链页： https://

**Comment by Arcitcgn** [comment]
{
    "title": "宏的自留地",
    "url": "https://arcitcgn.cn/",
    "avatar": "https://cdn.afdelivr.top/npm/arcitcgn-assets-public@2022.7.24/CDN/Personal%20assets/avatar-1.jpg",
    "screenshot": "https://bu.dusays.com/2022/07/16/62d2759e20525.png",
    "description": "一名初中生的小破站",
    "keywords": ""
}

**Comment by Arcitcgn** [comment]
I think I need a change.

**Comment by BowenYoung** [comment]
> I think I need a change.

You can open another issue and I'll close this. Then you can change your information anytime you want.😊
